module.exports = {
   // Core
   collations: false,
   engines: false,
   // Tools
   processesList: false,
   usersManagement: false,
   variables: false,
   // Structure
   databases: true,
   tables: false,
   views: false,
   triggers: false,
   routines: false,
   functions: false,
   schedulers: false,
   // Settings
   tableAdd: false,
   viewAdd: false,
   triggerAdd: false,
   routineAdd: false,
   functionAdd: false,
   schedulerAdd: false,
   databaseEdit: false,
   schemaEdit: false,
   tableSettings: false,
   viewSettings: false,
   triggerSettings: false,
   routineSettings: false,
   functionSettings: false,
   schedulerSettings: false,
   indexes: false,
   foreigns: false,
   sortableFields: false,
   zerofill: false
};
